language: ruby
rvm:
  - 2.2.0
  - 2.1.5
  - 2.0.0
  - 1.9.3

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database elefant_test;' -U postgres
  - cp test/config.yml.example test/config.yml
